global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          group: "prometheus"

  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]
        labels:
          group: "grafana"

  - job_name: "api_gateway"
    static_configs:
      - targets: ["api_gateway:8000"]
        labels:
          group: "api_gateway"

  - job_name: "authentication"
    static_configs:
      - targets: ["authentication:4001"]
        labels:
          group: "authentication"

  - job_name: "audit"
    static_configs:
      - targets: ["audit:4002"]
        labels:
          group: "audit"

  - job_name: "products"
    static_configs:
      - targets: ["products:4003"]
        labels:
          group: "products"

  - job_name: "payment"
    static_configs:
      - targets: ["payment:4004"]
        labels:
          group: "payment"

  # - job_name: "categories"
  #   static_configs:
  #     - targets: ["categories:4005"]
  #       labels:
  #         group: "categories"

  - job_name: "stores"
    static_configs:
      - targets: ["stores:4007"]
        labels:
          group: "stores"

  - job_name: "notification"
    static_configs:
      - targets: ["notification:4006"]
        labels:
          group: "notification"

  - job_name: "inventory"
    static_configs:
      - targets: ["inventory:4008"]
        labels:
          group: "inventory"
  - job_name: "cart"
    static_configs:
      - targets: ["cart:4009"]
        labels:
          group: "cart"

  - job_name: "tenant"
    static_configs:
      - targets: ["tenant:4010"]
        labels:
          group: "tenant"

  - job_name: "review"
    static_configs:
      - targets: ["review:4011"]
        labels:
          group: "review"

  - job_name: "orders"
    static_configs:
      - targets: ["orders:4012"]
        labels:
          group: "orders"

  # - job_name: "color"
  #   static_configs:
  #     - targets: ["color:4013"]
  #       labels:
  #         group: "color"

  # - job_name: "view"
  #   static_configs:
  #     - targets: ["view:4014"]
  #       labels:
  #         group: "view"

  - job_name: "rabbitmq"
    static_configs:
      - targets: ["rabbitmq:15672"]
        labels:
          group: "rabbitmq"

  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
        labels:
          group: "redis"
